language: cpp
dist: focal
compiler:
- g++
os:
- linux
script:
- mkdir include/
- wget https://github.com/nlohmann/json/releases/download/v3.10.4/json.hpp -P include/
- g++ CPP/main.cpp -lpthread -lcurl -I include/ -o CPP/main
