language: cpp
sudo: required
dist: bionic
compiler:
- g++
os:
- linux
script:
- sudo wget https://github.com/nlohmann/json/releases/download/v3.10.4/json.hpp -P /usr/include/
- cd CPP/ && g++ main.cpp -lpthread -lcurl -o main
