name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: g++ CPP/main.cpp -o CPP/main
