name: Mac
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: mkdir include/
      - run: wget https://github.com/nlohmann/json/releases/download/v3.10.4/json.hpp -P include/
      - run: g++ CPP/main.cpp -std=c++11 -lpthread -lcurl -I include/ -o CPP/main
